// <auto-generated />
using System;
using LondonHeathrow.Pa.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LondonHeathrow.Pa.Web.Migrations
{
    [DbContext(typeof(PaDbContext))]
    [Migration("20230715164221_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LondonHeathrow.Pa.Web.Data.DeviceData", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ConnectionId")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Device");

                    b.HasData(
                        new
                        {
                            Id = "test-device-01",
                            CreatedBy = new Guid("abce1577-0eb6-4508-8d33-17ebd2b10599"),
                            CreatedDate = new DateTime(2023, 7, 15, 16, 42, 21, 425, DateTimeKind.Utc).AddTicks(3470),
                            ModifiedBy = new Guid("abce1577-0eb6-4508-8d33-17ebd2b10599"),
                            ModifiedDate = new DateTime(2023, 7, 15, 16, 42, 21, 425, DateTimeKind.Utc).AddTicks(3480),
                            Name = "test device 01"
                        });
                });

            modelBuilder.Entity("LondonHeathrow.Pa.Web.Data.UserData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("abce1577-0eb6-4508-8d33-17ebd2b10599"),
                            CreatedBy = new Guid("abce1577-0eb6-4508-8d33-17ebd2b10599"),
                            CreatedDate = new DateTime(2023, 7, 15, 16, 42, 21, 425, DateTimeKind.Utc).AddTicks(5310),
                            DisplayName = "Admin",
                            FirstName = "Admin",
                            LastName = "User",
                            ModifiedBy = new Guid("abce1577-0eb6-4508-8d33-17ebd2b10599"),
                            ModifiedDate = new DateTime(2023, 7, 15, 16, 42, 21, 425, DateTimeKind.Utc).AddTicks(5310)
                        });
                });

            modelBuilder.Entity("LondonHeathrow.Pa.Web.Data.DeviceData", b =>
                {
                    b.HasOne("LondonHeathrow.Pa.Web.Data.UserData", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LondonHeathrow.Pa.Web.Data.UserData", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("LondonHeathrow.Pa.Web.Data.UserData", b =>
                {
                    b.HasOne("LondonHeathrow.Pa.Web.Data.UserData", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LondonHeathrow.Pa.Web.Data.UserData", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");
                });
#pragma warning restore 612, 618
        }
    }
}
